### PR TITLE
BLOXINF-759: Implement endpoint to store slashing history

### PR DESCRIPTION
**Pull request by roman-blox**

### CODE REVIEW

**Comment by alonmuroch** [comment]
@roman-blox @lior-blox I think a better design for this would be:
1) pull instead of push, that is, the wallet/ BloxLive should autonomously pull the information and not be pushed.
2) validation on the info should be done somehow (do we have all epochs for example)
3) the fetching part should use standard RPC calls so if a user wants to fetch it from somewhere else (for whatever reason) they can

**Comment by roman-blox** [comment]
@alonmuroch do you mean to pull this data from the beacon node server?

**Comment by olegshmuelov** [comment]
@roman-blox @lior-blox should we consider to read/update the slashing history in one request for all accounts (public keys) in the storage? and not one by one?

**Comment by roman-blox** [comment]
@olegshmuelov we may have a case when we need to update a slashing history for one specific account. And on the architecture level, it's more clear then do a batch update. If we really need that functionality, we may add an additional endpoint like to update a bunch of accounts, but I'm not sure we really need that.

**Review by olegshmuelov — APPROVED** [review]

**Pull request merged**
